language: java
jdk:
- openjdk7
- oraclejdk7
env:
- TERM=dumb
install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku labs:enable pipelines
- heroku plugins:install git://github.com/heroku/heroku-pipeline.git
before_script:
- "./gradlew build"
script:
- "./gradlew check"
deploy:
  provider: heroku
  api_key:
    secure: B/keF11I0rsOlsSsZnh2lKNhWes80M23u2n+TQ0FGxHnD4RUrVnIChzw+ytyjzv1ub0joNN5OrLazHDycmOfQCvBSRSLx2GaesRUR0kmwTnSz+m4PWmIXhd/AZ34atIDo5VQ3lxfCnCd3c5OqFfimJJ1cO8KpQifD1TAL71tedU=
  app: aegirproduct
  strategy: git
  on:
    repo: agirmar92/sparkIt
after_deploy:
- "./bin/test_and_promote"
